language: java

services:
  - mysql

jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
    - openjdk8

script:
  - ant test

notifications:
    - email: false  # Desactivamos las notificaciones por email para evitar spam