language:
    - java

services:
    - mysql

jdk:
    - oraclejdk8
    - openjdk7

before_install:
    - mysql -u root < script.sql

script:
    - mvn clean test
    - ls -lah

dist:
    - trusty

sudo:
    - false

notifications:
    - email: false  # Desactivamos las notificaciones por email para evitar spam