language: java

services:
  - mysql

jdk:
    - oraclejdk8
    - oraclejdk7

install: ant deps

sudo: false
script:
  - mvn test -B

notifications:
    - email: false  # Desactivamos las notificaciones por email para evitar spam